config/routes.rb
Rails.application.routes.draw do

  root to: "articles#index"

  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy_user"

  get "/login", to: "sessions#new", as: "new_session"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create", as: "create_session"

  get "/about", to: "about#show", as: "about"

  get "/munis/:id", to: "munis#show", as: "muni"

  get "/articles/new", to: "articles#new", as: "new_article"
  post "/articles", to: "articles#create"
  get "/articles/:id", to: "articles#show", as: "article"
  get "/articles/:id/edit", to: "articles#edit", as: "edit_article"
  patch "/articles/:id", to: "articles#update"
  delete "/articles/:id", to: "articles#destroy", as: "destroy_article"

  patch "/comments/:id", to: "comments#update", as: "update_comment"
end

# TODO: In many cases, Ruby styleguides will suggest using single quoted strings
#       instead of double quotes when you don't need string interpolation or
#       special symbols. This is an application-wide suggestion (just that- a
#       suggestion. This is not mandatory.).

app/models/article.rb
class Article < ActiveRecord::Base
  #TODO add default article code

  has_uploadcare_file :file

  before_validation :default_values

  validates :title, length: {in: 2..75}, presence: true
  validates :content, length: {in: 2..2000}, presence: true

  belongs_to :muni
  belongs_to :user
  has_many :comments

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  # example of a custom scope
  # this behaves just like a class method, with the advantage that we can "chain" off our query
  scope :with_vote_counts, -> {
    joins(:comments)
      .select("articles.*, SUM(comments.vote) as vote_total")
      .group("articles.id")
      .order("articles.vote_total DESC")
  }

  # example Article class method
  # def self.by_vote
  #   all.sort { |x,y| y.vote_total <=> x.vote_total} # TODO: inefficient in-memory sort!
  # end

  # example article instance method, with caching
  # def vote_total
  #   @vote_total ||= comments.sum(:vote) # but watch out this count is stale!
  # end


  private

  def default_values
    self.image = "https://ucarecdn.com/419db702-51f4-4665-a2ca-d23739a97b71/" if self.image == ""
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include AuthHelper
  include ApplicationHelper
#TODO should I remove the contextual reasons why a user isn't able to do an action on a route?

  def index
    @articles = Article.with_vote_counts.paginate(:page => params[:page], :per_page => 9)
    @munis = Muni.all
  end

  def show
    @article = Article.find(params[:id])
    return if current_user.nil?
    @comment = Comment.where(:article_id=>@article.id).where(:user_id=>current_user.id)[0]
    @comment = Comment.new if @comment.nil?
    @comment.user_id = current_user.id
    @comment.article_id = @article.id
    @comment.save
  end

  def new
    @article = Article.new
    render :new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = session[:user_id]
    @muni = Muni.find(@article.muni_id)
    if @article.save
      @muni.articles.push(@article)
      flash[:success] = "Your article titled \"#{@article.title}\" was successfully created"
      redirect_to article_path(@article)
    else
      flash[:notice] = "Cannot create your post: #{@article.errors.full_messages.join(', ')}."
      redirect_to new_article_path
    end
  end

  def edit
    @article = Article.find(params[:id])
    auth_fail("edit other people's article information!", @article) if !auth_route(@article.user)
  end

  def update
    set_article
    if auth_route(@article.user)
      if @article.update(article_params)
        flash[:success] = "#{@article.title} successfully updated"
        redirect_to article_path
      else
        render :edit
      end
    else
      auth_fail("update other people's articles", article_path)
    end
  end

  def destroy
    set_article
    if auth_route(@article.user)
      @user = @article.user
      @article.destroy
      flash[:success] = "Your article titled \"#{@article.title}\" was deleted."
      redirect_to user_path(@user)
    else
      auth_fail("delete other people's articles", article_path)
    end
  end

private

  def article_params
    params.require(:article).permit(:title, :content, :image, :muni_id)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_form.html.erb
<div class = "col-md-4 col-md-offset-4">
  <div class = "NewArticle">
    <%= bootstrap_form_for @article do |f| %>
      <%= f.text_field :title, placeholder: 'Title' %>
      <%= f.text_area :content, placeholder: 'Content' %>
      <%= f.collection_select :muni_id, Muni.order(:name),:id,:name, style: 'width: 100%;'%><br>
      <%= f.uploadcare_uploader :image, :data => {:images_only => true, :image_shrink => "1000x1000", :clearable => true }%>
      <br><br>
      <div class = "EditButton">
        <%= f.submit @article.new_record? ? "Create Post" : "Update Post"%>
      </div>
    <% end %>
    <div class = "CancelButton">
      <%= button_to "Cancel", :back, method: :get, :class=>"ruby-link btn btn-info btn-default btn-md inline" %>
    </div>
    <br><br>
  </div>
</div>

app/views/articles/edit.html.erb
<!-- TODO: Don't use <strong> tags or <br /> tags, use CSS styles -->
<h2><strong>Edit Your Post</strong></h2>
<br><br>

<%= render "article_form" %>

app/views/articles/index.html.erb
<div class="col-xs-12">
  <div class="flash-message-container">
    <%= flash_messages %>
  </div>
  <div class="newuserimage">
    <% if current_user == nil %>
      <img class="newmain img-responsive" src="http://i.imgur.com/f5nkiF7.png?1">
    <% end %>
  </div>
  <div class="brand-image show-mobile">
    <img class="img-responsive" src="https://i.imgur.com/EtptcPf.png">
  </div>
  <div class="newusertext">
    <% if current_user == nil %>
      <h1 class="text-center splash-title">Munilol</h1>
      <h2 class="text-center splash-title2">Public Transit At Its Finest</h2>
    <% end %>
  </div>
  <div class= "index-container col-xs-12 container-fluid well">
    <div class = "alert-message-container row">
      <div class="alert alert-danger" role"alert">
        <!-- TODO: Remove inline styles, add them to CSS -->
        <h5 id = "alert_message" style= "color:red; text-align: center;"> </h5>
      </div>
    </div>

    <% @articles.each do |article| %>
      <%= link_to article_path(article) do %>
        <div class="column col-xs-12 col-s-6 col-md-6 col-lg-4" style="padding: 3px">
          <div class="card card-inverse image-index" style="background-image: url('<%=article.image %>')">
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<%= render :partial => "layouts/paginate"%>

app/views/articles/new.html.erb
<%= flash_messages %>
<!-- TODO: Don't use <strong> tags or <br /> tags, use CSS styles -->
<h2><strong>Create New Post!</strong></h2>
<br><br>

<%= render "article_form" %>

app/views/articles/show.html.erb
<%= flash_messages %><br>
<div class="col-xs-12 col-md-10 col-md-offset-1 show-page-container">
  <div class="panel panel-default">
    <div class = "col-xs-12">
      <div class ="col-md-8 col-xs-9 col-md-offset-2 col-xs-offset-0">
        <div class="panel-image"><br><br>
          <img class="img-responsive img-rounded" <img src="<%= @article.image %>" data-toggle="modal" data-target="#myModal" style="width:auto; height:350px; margin: 0 auto; margin-top: -20px; cursor: pointer;" >
        </div>
      </div>
      <div class="col-xs-3 col-sm-2 col-lg-1" style="height:50vh"><br>
        <div class="vertically-align-force">
          <% if current_user != nil %>
            <%= form_for @comment, url: update_comment_path(@article.id), :remote => true do |f| %>
              <%= f.hidden_field :vote, :value => 1 %>
              <%= f.submit :type => :image, :class => "#{"grayed " if @comment.vote <= 0}up-vote img-responsive", :src => "https://i.imgur.com/QHTUl49.png"%>
            <% end %>
            <h1 class="vote-total text-center" data-vote="<%= @comment.vote %>"><%= @article.vote_total %></h1>
            <%= form_for @comment, url: update_comment_path(@article.id), :remote => true  do |f| %>
              <%= f.hidden_field :vote, :value => -1 %>
              <%= f.submit :type => :image, :class => "#{"grayed " if @comment.vote >= 0}down-vote img-responsive", :src => "https://i.imgur.com/NPKsG2K.png"%>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <h3 class="text-center" style="text-decoration:underline"><strong><%= @article.title %></strong></h3>
      <p style="font-style:italic"> posted <%= time_ago_in_words(@article.created_at) %> ago by <%= link_to @article.user.first_name, user_path(@article.user) %> while riding the <%= link_to @article.muni.name, muni_path(@article.muni), method: :get %></p>
      <p><%= @article.content %></p>
    </div>
    <% if current_user != nil && current_user.id == @article.user.id %>
    <div class="buttonrow">
    <%= link_to "Edit Article", edit_article_path, method: :get, :class=>"ruby-link btn btn-info btn-primary btn-md inline" %>
      <button class="ruby-link btn btn-danger inline btn-primary btn-md inline" type="button" data-toggle="collapse" data-target="#delete" aria-expanded="false" aria-controls="collapseExample">Delete Article</button><br>
        <div class = "row">
          <div class="collapse" id="delete"><br>
            <div class="well col-xs-6 col-xs-offset-3">
              <h5 class="inline"> Are you sure you want to delete your article? </h5>
                <button class="ruby-link btn-danger btn-primary btn-sm inline">
                  <%= link_to "Delete Article", destroy_article_path, method: :delete, :class=>"ruby-link"%>
                </button>
                <button class = "btn-success btn-primary btn-sm inline" data-toggle="collapse" data-target="#delete" aria-expanded="false" aria-controls="collapseExample">
                Cancel
                </button>
            </div>
          </div>
        </div>
    </div>
    <% end %><br>
    <div class="panel-footer text-center">
      <%= social_share_button_tag(@article.title, :image => "https://munilol.herokuapp.com/#{article_path(@article)}", desc: "#{@article.title}") %>
    </div>
  </div>
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        </div>
        <div class="modal-body">
          <img class="modal-img img-responsive" <img src="<%= @article.image %>">
        </div>
      </div>
    </div>
  </div>
</div>
<!-- </div> -->