config/routes.rb
Rails.application.routes.draw do

  root to: "articles#index"

  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy_user"

  get "/login", to: "sessions#new", as: "new_session"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create", as: "create_session"

  get "/about", to: "about#show", as: "about"

  get "/munis/:id", to: "munis#show", as: "muni"

  get "/articles/new", to: "articles#new", as: "new_article"
  post "/articles", to: "articles#create"
  get "/articles/:id", to: "articles#show", as: "article"
  get "/articles/:id/edit", to: "articles#edit", as: "edit_article"
  patch "/articles/:id", to: "articles#update"
  delete "/articles/:id", to: "articles#destroy", as: "destroy_article"

  patch "/comments/:id", to: "comments#update", as: "update_comment"
end

# TODO: In many cases, Ruby styleguides will suggest using single quoted strings
#       instead of double quotes when you don't need string interpolation or
#       special symbols. This is an application-wide suggestion (just that- a
#       suggestion. This is not mandatory.).

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  extend FriendlyId

  before_validation :default_values

  friendly_id :full_name, use: [:slugged, :finders]

  # TODO: You need to add a space before the closing brace for each validation
  validates :email, uniqueness: true, length: { in: 2..150}, presence: true
  validates :first_name, length: { in: 2..50}, presence: true
  validates :last_name, length: { in: 2..75}, presence: true

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :articles
  has_many :munis, :through => :articles
  has_many :comments, :through => :articles

  private

  def default_values
    # TODO: Host image locally for stability
    # TODO: Use if self.image instead of comparing to an empty string since
    #       empty strings are falsey
    self.image = "https://ucarecdn.com/1386c488-f2db-4b63-959f-32656a7e35c6/" if self.image == ""
    self.full_name = "#{self.first_name} #{self.last_name}"
  end


  # TODO: Private doesn't work if you are defining a method on a specific object,
  #       self in this case. You need to add private_class_method to define class
  #       methods as private
  private_class_method def self.confirm(params)
    # TODO: Why call .first if emails need to be unique? There should only be
    #       one user for a given email address.
    @user = User.where("email ILIKE ?", params[:email]).first
    @user.try(:authenticate, params[:password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include AuthHelper

  def new
    @user = User.new
    render :new
  end

  def create
    # TODO: This method needs a more descriptive name. Maybe create_user? It's
    #       not immediately clear what it does without scrolling down. Also,
    #       why is this necessary? You should just write @user = User.new(user_params)
    #       in the create method. I'm not aware of any reason to break this out into a private method.
    set_user
    if @user.save
      login(@user)
      flash[:notice] = "User account created! Welcome to Munilol"
      redirect_to @user
    else
      flash[:notice] = "There was a problem creating your account. #{@user.errors.full_messages.join(', ')}."
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.order("created_at DESC")
    render :show
  end

  def edit
    @user = User.find(params[:id])
    # TODO: Refactor to use 'unless' instead of ! and if
    auth_fail("edit other people's user information!", @user) if !auth_route(@user)
  end

  def update
    @user = User.find(params[:id])
    if auth_route(@user)
      if @user.update(user_params)
        flash[:success] = "Your profile was successfully updated"
        redirect_to @user
      else
        render :edit
      end
    else
      auth_fail("update other people's user information!", @user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    if auth_route(@user)
      Comment.delete_all(:user => @user.id)
      Article.delete_all(:user => @user.id)
      @user.destroy
      flash[:success] = "Your account has been deactivated."
      redirect_to root_path
    else
      auth_fail("Your account could not be deactivated.", user_path(@user))
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :full_name, :email, :password, :image)
  end

  def set_user
    @user = User.new(user_params)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="EditProfile">
      <%= bootstrap_form_for @user do |f| %>
      <%= f.text_field :first_name, placeholder: 'First Name' %>
      <%= f.text_field :last_name, placeholder: 'Last Name' %>
      <%= f.email_field :email, placeholder: 'Email' %>
      <%= f.password_field :password, placeholder: 'Password' %><br>
      <%= f.uploadcare_uploader :image, :data => {:images_only => true, :crop => "500x500 minimum", :image_shrink => "500x500", :clearable => true } %>
      <br><br>
    <div class="CreateButton">
      <%= f.submit @user.new_record? ? "Create Account" : "Update Profile"  %>
    </div>
    <% end %>
    <div class="CancelButton">
      <%= button_to "Cancel", :back, method: :get, :class=>"ruby-link btn btn-info btn-default btn-md" %>
    </div>
    <br><br>
  </div>
</div>

app/views/users/edit.html.erb
<h2><strong>Edit Your Profile</strong></h2>
<br><br>

<div class="row">
  <%= render "user_form" %>
</div>

<div class="text-center">
  <% if current_user != nil && current_user.id == @user.id %>
    <div class="row userbuttons">
      <button class="ruby-link btn btn-danger inline btn-primary btn-md inline" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Deactivate Account</button>
    </div>
    <div class="row">
      <div class="collapse" id="collapseExample">
        <div class="well col-xs-4 col-xs-offset-4">
          <h5 class="inline">
            Are you sure you want to deactivate your account?
          </h5>
          <button class="ruby-link btn-danger btn-primary btn-sm inline">
            <%= link_to "Deactivate", destroy_user_path(@user), method: :delete, :class=>"ruby-link"%>
          </button>
          <button class="btn-success btn-primary btn-sm inline" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Cancel
          </button>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br><br>

app/views/users/new.html.erb
<%= flash_messages %>
<h2><strong>Sign Up!</strong></h2>
<br><br>

<%= render "user_form" %>

app/views/users/show.html.erb
<div class="flash-message-container">
  <%= flash_messages %>
</div>
<br>
<% if current_user != nil && current_user.id == @user.id %>
  <div class="dropdownprofile">
    <div class="cog glyphicon glyphicon-cog"></div>
    <div class="dropdown-content"><br><br>
      <%= link_to current_user.first_name + "\'s Profile", user_path(current_user) %><br><br>
      <%= link_to "Profile Settings", edit_user_path(current_user) %><br><br>
      <%= link_to "Log Out", logout_path %><br>
    </div>
  </div>
<% end %>
<br>
<div class="ProfilePhoto">
  <img src="<%= @user.image%>" class="product_img img-responsive img-circle">
</div>
<h2><%= @user.first_name %>
  <%= @user.last_name %>'s Profile Page
</h2>
<h4>Date Joined:
  <%= @user.created_at.localtime.strftime("%B #{@user.created_at.day.ordinalize}, %Y") %>
</h4>
<div class="index-container col-xs-12 container-fluid well">
  <% if @user.articles.distinct.count < 1 || nil %>
    <p>Are you telling me you haven't seen anything funny on the Muni yet?</p>
    <p><%= link_to "Click here", new_article_path %> to share now!</p>
  <% end %>
  <% @articles.each do |article| %>
    <%= link_to article_path(article) do %>
      <div class="column col-xs-12 col-s-6 col-md-6 col-lg-4" style="padding: 3px">
        <div class="card card-inverse image-index" style="background-image: url('<%=article.image %>')"></div>
      </div>
    <% end %>
  <% end %>
  <br/>
</div>