config/routes.rb
Rails.application.routes.draw do

  root to: "articles#index"

  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy_user"

  get "/login", to: "sessions#new", as: "new_session"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create", as: "create_session"

  get "/about", to: "about#show", as: "about"

  get "/munis/:id", to: "munis#show", as: "muni"

  get "/articles/new", to: "articles#new", as: "new_article"
  post "/articles", to: "articles#create"
  get "/articles/:id", to: "articles#show", as: "article"
  get "/articles/:id/edit", to: "articles#edit", as: "edit_article"
  patch "/articles/:id", to: "articles#update"
  delete "/articles/:id", to: "articles#destroy", as: "destroy_article"

  patch "/comments/:id", to: "comments#update", as: "update_comment"
end

# TODO: In many cases, Ruby styleguides will suggest using single quoted strings
#       instead of double quotes when you don't need string interpolation or
#       special symbols. This is an application-wide suggestion (just that- a
#       suggestion. This is not mandatory.).

app/views/layouts/_paginate.html.erb
<div class="col-xs-12">
  <div class="text-center pagination-user pagination-user-desktop">
    <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
  </div>
</div>
<div class="col-xs-12">
  <div class="text-center pagination-user pagination-user-mobile show-mobile">
    <%= will_paginate @articles, renderer: BootstrapPagination::Rails, :page_links => false %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Munilol</title>
  <!-- TODO: Group your imported javascripts together and stylesheets together.
   External packages should go above all custom sheets -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="turbolinks-cache-control" content="no-cache">
  <!-- TODO: Looks like you have bootstrap installed locally but are using CDNs for
  other packages. You should serve all assets in a consistent manner. -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
  <%= include_uploadcare_widget_from_cdn version: "2.9.0", min: true %>
  <script>
  UPLOADCARE_LOCALE = "en";
  UPLOADCARE_TABS = "file url camera facebook gdrive dropbox instagram flickr skydrive";
  UPLOADCARE_PUBLIC_KEY = "e6aad8d63e7e221b9e3f";
  </script>
</head>
<body>
  <!-- TODO: Keep consistent spacing when applying attributes to HTML elements
  ex. Keep consistent between <div class = "nav-div"> (spaces) and
  <div class="nav-div"> (no spaces) Style matters! -->
  <div class = "col-xs-12">
    <div class = "nav-div">
      <header>
        <nav class="navbar navbar-default navbar-fixed-top">
          <!-- TODO: Move inline styles to stylesheets -->
          <div class="col-xs-12 navbar-header" style="padding-left:-10px">
            <div class="col-xs-3 pull-left">
              <a href="/" class="navbar-brand"><img class = "img-responsive" src="https://i.imgur.com/4X0lgTb.png"></a>
            </div>
            <div class="col-xs-9 pull-right">
              <ul class="nav navbar-nav v-align pull-right">
                <li style="margin-top: 12px;">
                  <select class="select-navbar js-example-basic-single" style="width: 100%;">
                    <% @munis.each do |muni| %>
                    <option></option>
                    <option value="<%= muni_path(muni.slug) %>"><%= muni.name %></option>
                    <% end %>
                  </select>
                </li>
                <li>
                  <% if current_user %>
                    <%= link_to "New Article", new_article_path, :class => "pull-right btn blue-grey lighten-3" %>
                  <% else %>
                    <%= link_to "New Article", new_session_path, :class => "pull-right btn blue-grey lighten-3" %>
                  <% end %>
                </li>
                <% if current_user %>
                  <ul class="nav navbar-nav">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, <%= current_user.first_name %>! <span class="glyphicon glyphicon-user pull-right"></span></a>
                        <ul class="dropdown-menu">
                          <!-- TODO: What about names that end with s? -->
                          <li><%= link_to current_user.first_name + "\'s Profile", user_path(current_user)%></li>
                          <li class="divider"></li>
                          <li><%= link_to "Profile Settings", edit_user_path(current_user) %></li>
                          <li class="divider"></li>
                          <li><%= link_to "Log Out", logout_path %></li>
                        </ul>
                    </li>
                  </ul>
              </ul>
              <% else %>
                <li><%= link_to "Sign up", new_user_path %></li>
                <li><%= link_to "Log In", new_session_path %></li>
              <% end %>
            </div>
          </div>
        </nav>
      </header>
    </div>
    <main>
      <div class ="row">
        <div class = "col-xs-12">
          <%= yield %>
        </div>
      </div>
    </main>
    <footer class="text-center">
      <p>Learn more about the <%= link_to "team!", about_path %></p>
    </footer>
    <div class="col-xs-12 navbar navbar-fixed-bottom bottom-nav-div">
      <div class="row" id="bottomNav">
        <% if current_user %>
          <div class="col-xs-3 text-center">
            <%= link_to :back do %><br>
              <i class="glyphicon glyphicon-chevron-left"></i>
            <% end %>
          </div>
          <div class="col-xs-3 text-center">
            <%= link_to root_path do %><br>
              <i class="glyphicon glyphicon-home"></i>
            <% end %>
          </div>
          <div class="col-xs-3 text-center">
            <%= link_to new_article_path do %><br>
              <i class="glyphicon glyphicon-plus"></i>
            <% end %>
          </div>
          <div class="col-xs-3 text-center">
            <%= link_to user_path(current_user) do %><br>
              <i class="glyphicon glyphicon-user"></i>
            <% end %>
          </div>
        <% else %>
          <div class="col-xs-3 text-center">
            <%= link_to :back do %><br>
              <i class="glyphicon glyphicon-chevron-left"></i>
            <% end %>
          </div>
          <div class="col-xs-3 text-center">
            <%= link_to root_path do %><br>
              <i class="glyphicon glyphicon-home"></i>
            <% end %>
          </div>
          <div class="col-xs-3 text-center">
            <%= link_to new_session_path do %><br>
              <i class="glyphicon glyphicon-plus"></i>
            <% end %>
          </div>
          <div class="col-xs-3 text-center">
            <%= link_to new_session_path do %><br>
              <i class="glyphicon glyphicon-log-in"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>
</html>